SELECT* FROM [CUSTOMER TABLES1] 


INSERT INTO [CUSTOMER TABLES1]
(NAME,SURNAME,BIRTHDATE,CİTY,COUNTRY,GENDER)
VALUES
('KÜBRA','TURAN','2017-02-03','KOCAELİ','TURKEY','K')

UPDATE [CUSTOMER TABLES1]
SET NATİON='TR' ,AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
DELETE FROM [CUSTOMER TABLES1] 
WHERE ID BETWEEN 6 AND 15




